// Generated by CoffeeScript 1.7.1
(function() {
  var Assertion, Paws, expect, i;

  expect = require('expect.js');

  Paws = require('../Source/Paws.coffee');

  Assertion = expect.Assertion;

  i = expect.stringify;

  Assertion.prototype.responsible = function() {
    expect(this.obj).to.be.a(Paws.Relation);
    return this.assert(this.obj.isResponsible, (function() {
      return 'expected ' + i(this.obj) + ' to be responsible';
    }), (function() {
      return 'expected ' + i(this.obj) + ' to be irresponsible';
    }));
  };

}).call(this);
